// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVBm3hE6-qiXkLrmXlMHNAB7OlpgrLP8U',
    appId: '1:1066003539451:web:cc182593cef96f4db3175e',
    messagingSenderId: '1066003539451',
    projectId: 'charlottewebsitei',
    authDomain: 'charlottewebsitei.firebaseapp.com',
    storageBucket: 'charlottewebsitei.appspot.com',
    measurementId: 'G-LFYNV224RG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCynF7GcFj_WCHqA3g-gUs2YPCxareAwFc',
    appId: '1:1066003539451:android:eabe6ab1caa2a397b3175e',
    messagingSenderId: '1066003539451',
    projectId: 'charlottewebsitei',
    storageBucket: 'charlottewebsitei.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyCjEUV0kIr2QZE2HQe10IUGqwbrYQMik',
    appId: '1:1066003539451:ios:f9907a1cbf6a0045b3175e',
    messagingSenderId: '1066003539451',
    projectId: 'charlottewebsitei',
    storageBucket: 'charlottewebsitei.appspot.com',
    iosClientId: '1066003539451-pso3oaq2tnekphavlqpank4g31uiamvc.apps.googleusercontent.com',
    iosBundleId: 'com.charlottelobry.app',
  );
}
